---
title: "Simulation"
output: github_document
---

```{r}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


Load key packages

```{r}
library(tidyverse)
library(readxl)
library(rvest)

set.seed(1031) #setting the seed makes sure you get the same random numbers everytime you run the simulation
```



## writing a simulation function 

```{r}
sim_mean_sd = function(samp_size, true_mean = 10, true_sd = 5) {

    sim_df = 
    tibble(
      x = rnorm(samp_size, true_mean, true_sd)
    )
  
  out_df = 
    sim_df |> 
    summarize(
      samp_mean = mean(x),
      samp_sd = sd(x)
    )
  
  return(out_df)
}

sim_mean_sd(samp_size = 30, true_mean = 4, true_sd = 12)
```

run this a lot of times ...

```{r}
sim_mean_sd(30)
```

run this using a for loop?

```{r}
output = vector("list", 1000)

for (i in 1:1000) {
  
  output[[i]] = sim_mean_sd(30)
  
} #once run, now you've ran this 1000 times and generated 1000 sd

#output

bind_rows(output) |> 
  summarize(
    ave_samp_mean = mean(samp_mean),
    SE_samp_mean = sd(samp_mean)) #can check 5 / sqrt(30) to check if sd_mean is similar  

```


